name: bert-finetune
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch>=2.0.0
      - torchvision
      - torchaudio
      - transformers>=4.35.0
      - peft>=0.4.0
      - datasets
      - sentencepiece
      - tqdm
      - datasets
      - scikit-learn
      - numpy
      - pandas

